---
- name: Create PostgreSQL database and roles for each trainee
  hosts: localhost
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Install psycopg2 library (required for Ansible PostgreSQL modules)
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
      become: true

    - name: Create the database
      community.postgresql.postgresql_db:
        name: "{{ trainee_name }}_simplechat"
        encoding: "UTF8"
        owner: "postgres"
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_port: "{{ db_port }}"

    - name: Execute SQL script for role creation and permissions
      community.postgresql.postgresql_query:
        query: |
          {% include sql_script_path %}
        db: postgres  # Use the default 'postgres' database for running queries
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_port: "{{ db_port }}"
